sonar.projectKey=s1d15_8.2CDevSecOps
sonar.organization=s1d15
sonar.host.url=https://sonarcloud.io
sonar.login=${1e457f868d4f1b690e6f5bc21a3350e28e3cd07e}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8